### ISSUE TITLE
Doesn't work with JetEngine pagnation

### ISSUE THREAD

**Issue by klecka** [MjHead/jet-engine-break-listing-by-months#2]
Everything works flawlessly but breaks the pagination for listing grid. The widget will not be visible anymore or simply doesn't work when using the correct querry ID

**Comment by therenoscene** [comment]
Hey @klecka 
in Query set a Query ID ex. "property_list"
Even if the Query is selected in the listing you picked in the General section of the Listing Grid enable and set "Custom Query" to the query the Listing has.
In the pagination set the Query ID to the same ex. "property_list"
same query id goes to "define( 'JET_ENGINE_BREAK_BY_QUERY_ID', 'property_list' );" where you are managing your constants

also in some of the instructions I found on setting the query for break it said to set the pagination to -1 in the query builder but I set it to what I want the pagination to be by and it seems to be working

at least this is what it took for me through trial and error.
